/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Clases.Contacto;
import static Vistas.Menu.directorio;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lourdes
 */
public class BorrarContacto extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel(){ //Creamos un modelo para poder modificar la tabla
    @Override
    public boolean isCellEditable(int f, int c){ //Este metodo sirve para evitar que las celdas sean editables
      // Deshabilitar la selección de filas, columnas y celdas
    tabla.setRowSelectionAllowed(false);
    tabla.setColumnSelectionAllowed(false);
    tabla.setCellSelectionEnabled(false);
    
        return false;
    }
    };
    /**
     * Creates new form BorrarContacto
     */
    public BorrarContacto() {
        initComponents();
        armarCabecera();
        cargarTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfBorrarContacto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jbBorrar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESE UN NUMERO DE TELÉFONO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Directorio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, -1));
        jPanel1.add(tfBorrarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 11, 129, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 398, 160));

        jbBorrar.setBackground(new java.awt.Color(255, 255, 255));
        jbBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbBorrar.setForeground(new java.awt.Color(0, 102, 153));
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, 31));

        jbSalir.setBackground(new java.awt.Color(255, 255, 255));
        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(0, 102, 153));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 69, 31));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GRIS AZULADO-1000x672.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
     dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        borrar();
        borrarContacto();
        cargarTodo();
    
    }//GEN-LAST:event_jbBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tfBorrarContacto;
    // End of variables declaration//GEN-END:variables
private void armarCabecera(){
    modelo.addColumn("DNI");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("Ciudad");
    modelo.addColumn("Dirección");
    modelo.addColumn("Teléfono");
    tabla.setModel(modelo);
}
private void borrar(){
    int f = tabla.getRowCount()-1;
    for(;f>=0;f--){
        modelo.removeRow(f); 
    }
}

private void cargarTodo(){
    TreeMap<Long,Contacto> d = directorio.getNumMasContactos();
    for(Map.Entry<Long,Contacto> entry : d.entrySet()){
            modelo.addRow(new Object[]{entry.getValue().getDni(),entry.getValue().getNombre(),entry.getValue().getApellido(),entry.getValue().getCiudad(),entry.getValue().getDireccion(),entry.getKey()});
        }
}

//private void borrarContacto(){
//    Long clave = Long.valueOf(tfBorrarContacto.getText());
//    directorio.borrarContacto(clave);
//}
private void borrarContacto() {
    try {
        String claveString = tfBorrarContacto.getText().trim(); // Eliminamos espacios en blanco

        if (!claveString.isEmpty()) {
            try {
                long clave = Long.parseLong(claveString);
                directorio.borrarContacto(clave);
                JOptionPane.showMessageDialog(this, "Contacto eliminado exitosamente.");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un número válido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar el número del contacto a eliminar.");
        }
    } catch (Exception e) {
        // Manejar otras excepciones que puedan surgir
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al eliminar el contacto. Por favor, intente nuevamente.");
    }
}
}
