/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Clases.Contacto;
import static Vistas.Menu.directorio;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lourdes
 */
public class BuscarporCiudad extends javax.swing.JInternalFrame {
private DefaultTableModel modelo = new DefaultTableModel(){ //Creamos un modelo para poder modificar la tabla
    @Override
    public boolean isCellEditable(int f, int c){ //Este metodo sirve para evitar que las celdas sean editables
        return false;
    }
};
    /**
     * Creates new form BuscarporCiudad
     */
    public BuscarporCiudad() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfCiudadBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESE EL NOMBRE DE UNA CIUDAD:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        tfCiudadBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCiudadBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(tfCiudadBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 130, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 397, 220));

        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(0, 102, 153));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 303, 76, 31));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Coincidencias:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GRIS AZULADO-1000x672.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
    dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jbSalirActionPerformed

    private void tfCiudadBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCiudadBuscarKeyReleased
       borrar();
       cargarDatos();
    }//GEN-LAST:event_tfCiudadBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tfCiudadBuscar;
    // End of variables declaration//GEN-END:variables
private void armarCabecera(){
    modelo.addColumn("DNI");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("Dirección");
    tabla.setModel(modelo);
}
private void borrar(){
    int f = tabla.getRowCount()-1;
    for(;f>=0;f--){
        modelo.removeRow(f);
    }
}

private void cargarDatos(){
    String ciudad = tfCiudadBuscar.getText();
    if(!(ciudad.isEmpty())){
    ArrayList<Contacto> lista = directorio.buscarContactos(ciudad);
        for (Contacto c : lista) {
            modelo.addRow(new Object[]{c.getDni(),c.getNombre(),c.getApellido(),c.getDireccion()});
        }
    }
}
}

